// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"scnu_acm_rank/biz/config"
	"scnu_acm_rank/biz/model"
)

func main() {
	h := server.Default()
	register(h)
	model.GetDB()
	config.Update <- struct{}{}
	h.Spin()
}
