// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"scnu_acm_rank/biz/middle"
)

func main() {
	h := server.Default()
	register(h)
	middle.GetDB()
	h.Spin()
}
