// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"log"
	handler "scnu_acm_rank/biz/handler"
	"scnu_acm_rank/biz/middle"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {

	auth, err := middle.GetJWT()
	if err != nil {
		panic(err)
	}
	errInit := auth.MiddlewareInit()

	if errInit != nil {
		log.Fatal("authMiddleware.MiddlewareInit() Error:" + errInit.Error())
	}

	r.GET("/ping", handler.Ping)

	competition := r.Group("/competition")
	competition.GET("/person", handler.CompetitionPerson)
	competition.GET("/group", handler.CompetitionGroup)
	competition.GET("/detail", handler.CompetitionDetail)
	// your code ...
	user := r.Group("/user")
	user.POST("/login", auth.LoginHandler)
	user.POST("/register", handler.Register)
}
