// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"log"
	handler "scnu_acm_rank/biz/handler"
	root2 "scnu_acm_rank/biz/handler/root"
	super2 "scnu_acm_rank/biz/handler/super"
	user2 "scnu_acm_rank/biz/handler/user"
	"scnu_acm_rank/biz/middle"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {

	auth, err := middle.GetJWT()
	if err != nil {
		panic(err)
	}
	errInit := auth.MiddlewareInit()

	if errInit != nil {
		log.Fatal("authMiddleware.MiddlewareInit() Error:" + errInit.Error())
	}

	r.GET("/ping", handler.Ping)

	competition := r.Group("/competition")
	competition.GET("/person", handler.CompetitionPerson)
	competition.GET("/group", handler.CompetitionGroup)
	competition.GET("/detail", handler.CompetitionDetail)

	// your code ...
	r.POST("/login", auth.LoginHandler)
	r.POST("/register", handler.Register)
	r.POST("sendEmail", handler.SendEmail)
	user := r.Group("/user")
	user.Use(auth.MiddlewareFunc())
	user.POST("/edit", user2.EditUser)
	user.GET("/detail", handler.UserDetail)
	user.POST("/createTeam", user2.CreateTeam)
	user.POST("/joinTeam", user2.JoinTeam)

	root := r.Group("/root")
	root.POST("/createCompetition", root2.CreateCompetition)
	root.POST("/updateConfig", root2.UpdateConfig)

	super := r.Group("/super")
	super.POST("/addRoot", super2.AddRoot)
}
